import nodemailer from "nodemailer";

export async function POST(req: Request) {
  try {
    const { name, email, message } = await req.json();

    if (!name || !email || !message) {
      return new Response(JSON.stringify({ error: "Missing required fields" }), {
        status: 400,
        headers: { "Content-Type": "application/json" },
      });
    }

    const isEmailConfigured = process.env.EMAIL_USER && process.env.EMAIL_PASS;

    if (!isEmailConfigured) {
      // Fallback for development if .env is not loaded or missing
      return new Response(JSON.stringify({ error: "Email service not configured. Please add EMAIL_USER and EMAIL_PASS to .env" }), {
        status: 500,
        headers: { "Content-Type": "application/json" },
      });
    }

    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    const mailOptions = {
      from: email,
      to: process.env.EMAIL_USER,
      subject: `New Portfolio Message from ${name}`,
      text: `Name: ${name}\nEmail: ${email}\n\nMessage:\n${message}`,
      html: `
        <div style="background-color: #050505; padding: 40px; font-family: 'Outfit', sans-serif; color: #fafafa;">
          <div style="max-width: 600px; margin: 0 auto; background: rgba(255,255,255,0.03); border: 1px solid rgba(124,58,237,0.2); border-radius: 32px; overflow: hidden; box-shadow: 0 20px 50px rgba(0,0,0,0.5);">
            
            <!-- Header Section -->
            <div style="background: linear-gradient(135deg, #7c3aed 0%, #a78bfa 100%); padding: 40px; text-align: center;">
              <div style="display: inline-block; padding: 12px; background: rgba(255,255,255,0.1); border-radius: 16px; margin-bottom: 20px;">
                <img src="https://img.icons8.com/ios-filled/50/ffffff/sent.png" width="30" height="30" style="display: block;" />
              </div>
              <h1 style="margin: 0; font-size: 28px; font-weight: 900; letter-spacing: -1px; text-transform: uppercase;">New Transmission</h1>
              <p style="margin: 10px 0 0; opacity: 0.8; font-weight: 500; letter-spacing: 2px; font-size: 10px; text-transform: uppercase;">Lead Captured from Portfolio</p>
            </div>

            <!-- Content Body -->
            <div style="padding: 40px;">
              <div style="margin-bottom: 30px;">
                <p style="text-transform: uppercase; font-size: 10px; font-weight: 900; color: #7c3aed; letter-spacing: 2px; margin-bottom: 8px;">Sender Details</p>
                <div style="background: rgba(255,255,255,0.05); padding: 20px; border-radius: 16px; border: 1px solid rgba(255,255,255,0.05);">
                  <p style="margin: 0; font-size: 18px; font-weight: 700;">${name}</p>
                  <p style="margin: 5px 0 0; font-size: 14px; opacity: 0.5;">${email}</p>
                </div>
              </div>

              <div style="margin-bottom: 30px;">
                <p style="text-transform: uppercase; font-size: 10px; font-weight: 900; color: #7c3aed; letter-spacing: 2px; margin-bottom: 8px;">Message Content</p>
                <div style="background: rgba(255,255,255,0.05); padding: 24px; border-radius: 16px; border-left: 4px solid #7c3aed;">
                   <p style="margin: 0; font-size: 16px; line-height: 1.6; opacity: 0.9;">${message}</p>
                </div>
              </div>

              <!-- CTA / Footer -->
              <div style="text-align: center; margin-top: 40px;">
                <a href="mailto:${email}" style="display: inline-block; background: #7c3aed; color: #ffffff; padding: 16px 32px; border-radius: 16px; text-decoration: none; font-weight: 900; font-size: 14px; text-transform: uppercase; letter-spacing: 1px; box-shadow: 0 10px 20px rgba(124,58,237,0.3);">
                  Reply to ${name.split(' ')[0]}
                </a>
              </div>
            </div>

            <!-- Bottom Note -->
            <div style="padding: 20px; text-align: center; border-top: 1px solid rgba(255,255,255,0.05); background: rgba(255,255,255,0.02);">
              <p style="margin: 0; font-size: 10px; opacity: 0.3; font-weight: 700; text-transform: uppercase; letter-spacing: 1px;">
                Generated by LOVE GHARIWALA PORTFOLIO ENGINE v1.0
              </p>
            </div>
          </div>
        </div>
      `,
    };

    await transporter.sendMail(mailOptions);

    return new Response(JSON.stringify({ success: true, message: "Email sent successfully" }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  } catch (error: any) {
    console.error("Email error:", error);
    return new Response(JSON.stringify({ error: "Failed to send email", details: error.message }), {
      status: 500,
      headers: { "Content-Type": "application/json" },
    });
  }
}
